# -*- coding: utf-8 -*-
"""Assignment_4_Sentiment Analysis_Deep

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKptj2aXQTR_eetI4mvYfBmkT_Qf4xln
"""

#Drive mounting
from google.colab import drive
drive.mount('/content/drive')

import re

negativeWordsList = []
positiveWordsList = []

with open("/content/drive/MyDrive/Data/NegativeWord.txt") as file: 
    for readLine in file:
        readLine = re.sub("\n", "", readLine)
        negativeWordsList.append(readLine)

with open("/content/drive/MyDrive/Data/PositiveWord.txt") as file:
    for readLine in file:
        readLine = re.sub("\n", "", readLine)
        positiveWordsList.append(readLine)

print(positiveWordsList)
print(negativeWordsList)

import csv

import os
import pandas as pd

tweets = []
path = '/content/drive/MyDrive/Data/Tweets/'
filenamesList = os.listdir('/content/drive/MyDrive/Data/Tweets/')
for filename in filenamesList:
  filepath = path + filename
  with open(filepath, encoding='utf-8') as filepath:
    dataframe = pd.read_csv(filepath)
    for text in dataframe['text'].to_list():
      print(BagOfWords(str(text)))
      PolarityCalculation(str(text))

def BagOfWords(tweet):
    wordDict = {}
    tweetwords = tweet.split()
    for word in tweetwords:
       wordDict[word] = 0
    for word in tweetwords:
       wordDict[word] += 1
    return wordDict

def PolarityCalculation(tweet_text):
    positiveList = []
    negativeList = []
    
    tweetsWords = tweet_text.split()
    for w in tweetsWords:
        if w in negativeWordsList:
            negativeList.append(w)
        elif w in positiveWordsList:
            positiveList.append(w)

    positiveWordsPersentLength = len(positiveList)
    negativeWordsPersentLength = len(negativeList)

    if negativeWordsPersentLength == positiveWordsPersentLength:
        polarityForTweet = "NONE"
    elif positiveWordsPersentLength > negativeWordsPersentLength:
        polarityForTweet = "POSITIVE"
    else:
        polarityForTweet = "NEGATIVE"
    print("Polarity for this tweet is: ", polarityForTweet)